# Generated by Django 2.2 on 2019-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('article', models.TextField()),
                ('website', models.URLField()),
                ('data', models.TimeField()),
            ],
        ),
    ]
