# Generated by Django 2.2 on 2019-06-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houselocation',
            name='data',
        ),
    ]
