# Generated by Django 2.2 on 2019-06-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapPage', '0002_remove_houselocation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselocation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
