# Generated by Django 2.2 on 2019-06-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapPage', '0003_houselocation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselocation',
            name='category',
            field=models.CharField(default='自殺', max_length=15),
        ),
    ]
