# Generated by Django 2.2 on 2019-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapPage', '0004_houselocation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('category', models.CharField(default='汽車擦撞', max_length=15)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
