# Generated by Django 2.2 on 2019-06-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapPage', '0005_trafficlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlocation',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='trafficlocation',
            name='lng',
            field=models.FloatField(default=None),
        ),
    ]
