# Generated by Django 2.2 on 2019-06-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapPage', '0006_auto_20190612_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='houselocation',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='houselocation',
            name='lng',
            field=models.FloatField(default=None),
        ),
    ]
